// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('4', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('4', async function() {
    await driver.get("http://admin-test.kokiska.cz/")
    await driver.findElement(By.css(".row-orders:nth-child(1) strong")).click()
    vars["price"] = await driver.findElement(By.css(".order-item > td:nth-child(4) > .tooltip-title:nth-child(1)")).getText()
    vars["price"] = await driver.executeScript("return parseFloat(arguments[0].replace(\',\', \'.\').replace(\' \', \'\'))", vars["price"])
    vars["priceVat"] = await driver.findElement(By.css("td:nth-child(4) > .tooltip-title > strong")).getText()
    vars["priceVat"] = await driver.executeScript("return parseFloat(arguments[0].replace(\',\', \'.\').replace(\' \', \'\'))", vars["priceVat"])
    console.log(vars["priceVat"])
    console.log(vars["price"])
    vars["a"] = await driver.findElement(By.css(".order-item > .help")).getText()
    console.log(vars["a"])
    if (!!await driver.executeScript("return (arguments[0].includes(\'21\'))", vars["a"])) {
      vars["x"] = await driver.executeScript("return Number ((arguments[0]) * 0.21) + (arguments[0])", vars["price"])
    } else if (!!await driver.executeScript("return (arguments[0].includes(\'20,00\'))", vars["a"])) {
    }
    console.log(vars["x"])
    vars["q"] = await driver.executeScript("return Math.round(arguments[0] * 100) / 100", vars["x"])
    console.log(vars["q"])
    console.log(vars["a"])
  })
})
