// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const assert = require('assert');

const FAQTest = function() {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });
  afterEach(async function() {
    await driver.quit();
  });
  it('FAQTest', async function() {
    await driver.get("http://test.kokiskashop.sk/najcastejsie-otazky-a-odpovede/");
    vars["faqurl"] = await driver.executeScript("return window.location.href");
    assert(vars["faqurl"].toString() === "http://test.kokiskashop.sk/najcastejsie-otazky-a-odpovede/");
    assert(await driver.getTitle() === "Najčastejšie otázky | Kokiskashop.sk");
    {
      const elements = await driver.findElements(By.css(".page__title"));
      assert(elements.length);
    }
    {
      const elements = await driver.findElements(By.css(".page__text"));
      assert(elements.length);
    }
    vars["faqQuestionSize"] = await driver.findElements(By.xpath("//*[@class=\'faq__box\']")).length;
    console.log("Number of questions = vars['faqQuestionSize']");
    vars["i"] = "1";
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars['faqQuestionSize'])) {
      await driver.findElement(By.xpath("//descendant::*[contains(@class, \'faq__status-wrap\')][vars['i']]")).click();
      vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"]);
      vars["faqQuestionSize"] = await driver.executeScript("return Number (arguments[0]) - 1", vars['faqQuestionSize']);
    }
  });
};

FAQTest();
