// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('kosik', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function kosikprazdny() {
    vars["url"] = await driver.executeScript("return window.location.href")
    if (!!await driver.executeScript("return (arguments[0] !== \'https://www.kokiskashop.cz/cz/kosik/produkty/\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//cz/kosik/produkty/")
    }
    vars["topMenuLinkSize"] = await driver.findElements(By.xpath("//*[@class=\'top-bar__menu-link\']")).length
    if (!!await driver.executeScript("return (arguments[0] < 5)", vars["topMenuLinkSize"])) {
      vars["pageWrapSize"] = await driver.findElements(By.xpath("//*[@class=\'page__wrap\']")).length
      assert(vars["pageWrapSize"].toString() == "2")
      vars["columnSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'extended-cart-panel__column\')]")).length
      assert(vars["columnSize"].toString() == "3")
      vars["titleSize"] = await driver.findElements(By.xpath("//*[@class=\'extended-cart-panel__title\']")).length
      assert(vars["titleSize"].toString() == "vars["columnSize"]")
      assert(await driver.findElement(By.xpath("//html/body/section[1]/section/div/div[1]/h2/strong")).getText() == "Nastavení")
      assert(await driver.findElement(By.xpath("//html/body/section[1]/section/div/div[1]/div[1]/label")).getText() == "Cizí měna")
    }
    if (!!await driver.executeScript("return (arguments[0] >= 5)", vars["topMenuLinkSize"])) {
      vars["cartItemSize"] = await driver.findElements(By.xpath("//div[@class=\'cart-items-container\']/div[@class=\'cart-item\']")).length
      while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
        await driver.findElement(By.css(".cart-item__delete-sign")).click()
        await driver.sleep(2000)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//div[@class=\'cart-items-container\']/div[@class=\'cart-item\']")).length
        console.log(vars["cartItemSize"])
      }
    } else if (!!await driver.executeScript("return (arguments[0] < 5)", vars["topMenuLinkSize"])) {
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item cart-item--admin\']")).length
      while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
        await driver.findElement(By.css(".cart-item__delete-sign")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item cart-item--admin\']")).length
      }
    }
    kosiknavigace()
    {
      const elements = await driver.findElements(By.css(".cart-empty__image"))
      assert(elements.length)
    }
    {
      const attribute = await driver.findElement(By.css("img.cart-empty__image")).getAttribute("src")
      vars["imgurl"] = attribute
    }
    assert(vars["imgurl"].toString() == "https://www.kokiskashop.cz/admin-prod/public/images//empty-cart.jpg")
    {
      const attribute = await driver.findElement(By.css("img.cart-empty__image")).getAttribute("alt")
      vars["txt1"] = attribute
    }
    assert(vars["txt1"].toString() == "Prázdný košík")
    assert(await driver.findElement(By.xpath("//*[@class=\'page-cart__title\']")).getText() == "Váš košík je prázdný...")
    assert(await driver.findElement(By.xpath("//*[@class=\'cart-empty__text\']")).getText() == "Máme široký sortimet zboží pro dům, zahradu i volný čas. Pokud potřebujete poradit s výběrem vhodného produktu, využijte naši telefonickou podporu. Jsme tu pro Vás.")
    {
      const attribute = await driver.findElement(By.css("a.page-cart__link")).getAttribute("href")
      vars["linkurl"] = attribute
    }
    assert(vars["linkurl"].toString() == "https://www.kokiskashop.cz/cz/kontakt/")
    assert(await driver.findElement(By.xpath("//*[@class=\'cart-buttons__button cart-buttons__button--green\']")).getText() == "Zpět k nákupu")
    {
      const attribute = await driver.findElement(By.css("a.cart-buttons__button--green")).getAttribute("href")
      vars["backurl"] = attribute
    }
    assert(vars["backurl"].toString() == "https://www.kokiskashop.cz/")
    assert(await driver.findElement(By.xpath("//*[@class=\'cart-eet\']")).getText() == "Podle zákona o evidenci tržeb je prodávající povinen vystavit kupujícímu účtenku. Zároveň je povinen zaevidovat přijatou tržbu u správce daně online")
  }
  async function kosiknavigace() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//cz/kosik/produkty/")
    }
    {
      const elements = await driver.findElements(By.xpath("//*[@class=\'cart-nav__wrap\']"))
      assert(elements.length)
    }
    vars["navStepSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step\')]")).length
    vars["navNumberSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-nav__number\']")).length
    vars["navLabelSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-nav__label\']")).length
    vars["navSeparatorSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-nav__separator\']")).length
    {
      const elements = await driver.findElements(By.xpath("//*[@class=\'cart-nav__shadow\']"))
      assert(elements.length)
    }
    {
      const attribute = await driver.findElement(By.css("img.cart-nav__shadow")).getAttribute("src")
      vars["imgurl"] = attribute
    }
    assert(vars["imgurl"].toString() == "https://www.kokiskashop.cz/admin-prod/public/images/cart-shadow.png")
    assert(vars["navStepSize"].toString() == "4")
    assert(vars["navStepSize"].toString() == "vars["navLabelSize"]")
    assert(vars["navStepSize"].toString() == "vars["navNumberSize"]")
    assert(vars["navSeparatorSize"].toString() == "3")
    {
      const elements = await driver.findElements(By.xpath("//*[@class=\'cart-nav__step  cart-nav__step--active\']"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--active\')]"))
      assert(elements.length)
    }
    if (!!await driver.executeScript("return (arguments[0] == \'https://test.kokiskashop.cz/cz/kosik/produkty/\')", vars["url"])) {
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item\']")).length
      if (!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
        {
          const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
          vars["activestepurl"] = attribute
        }
        assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/produkty/")
      }
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "0")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "1")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "2")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "3")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    } else if (!!await driver.executeScript("return (arguments[0] == \'https://www.kokiskashop.cz/cz/kosik/doprava/\')", vars["url"])) {
      {
        const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
        vars["activestepurl"] = attribute
      }
      assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/doprava/")
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "1")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "2")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "3")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    } else if (!!await driver.executeScript("return (arguments[0] == \'https://test.kokiskashop.cz/cz/kosik/informace-o-vas/\')", vars["url"])) {
      {
        const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
        vars["activestepurl"] = attribute
      }
      assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/informace-o-vas/")
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "2")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "3")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    } else if (!!await driver.executeScript("return (arguments[0] == \'https://www.kokiskashop.cz/cz/kosik/rekapitulace/\')", vars["url"])) {
      {
        const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
        vars["activestepurl"] = attribute
      }
      assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/rekapitulace/")
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "3")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    }
    assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__label\')][1]")).getText() == "Nákupní košík")
    assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[2]")).getText() == "Doprava a platba")
    assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[2]")).getText() == "Adresa")
    assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[2]")).getText() == "Dokončení")
  }
  async function hmotnostS() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(2000)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[5]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Hračky pro nejmenší")).click()
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars["i"]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 2 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(1500)
        vars["url"] = await driver.executeScript("return window.location.href")
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      console.log(vars["url"])
    } while(!!await driver.executeScript("return (!arguments[0].includes(\'/kosik/produkty\'))", vars["url"]))
  }
  async function hmotnostM() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[4]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Autodoplňky")).click()
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars["i"]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 10 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[1]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Bazény a vířivky")).click()
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars["i"]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 30 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'header__cart-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostXL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[1]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Grily a krby")).click()
    await driver.findElement(By.id("box-tab-menu")).click()
    {
      const dropdown = await driver.findElement(By.id("box-tab-menu"))
      await dropdown.findElement(By.xpath("//option[. = 'Od nejdražšího']")).click()
    }
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars["i"]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 50 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostXXL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    await driver.findElement(By.id("main-search-inputfield")).sendKeys("marimex trampolína")
    await driver.findElement(By.id("main-search-inputfield")).sendKeys(Key.ENTER)
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars["i"]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 70 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@id=\"snippet-front-basket-head\"]/div/div/div[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@id=\"snippet-front-basket-head\"]/div/div/div[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostXXXL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    await driver.findElement(By.id("main-search-inputfield")).sendKeys("věž posilovací dvoupozicová")
    await driver.findElement(By.id("main-search-inputfield")).sendKeys(Key.ENTER)
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars["i"]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 150 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function odhlaseni() {
    await driver.get("https://test.kokiskashop.cz//")
    vars["topMenuLinkSize"] = await driver.findElements(By.xpath("//*[@class=\'top-bar__menu-link\']")).length
    if (!!await driver.executeScript("return (arguments[0] < 6)", vars["topMenuLinkSize"])) {
      await driver.findElement(By.css(".top-dropdown__arrow-box:nth-child(3) > .top-dropdown__arrow")).click()
      await driver.findElement(By.css(".top-dropdown__item:nth-child(6)")).click()
      assert(await driver.findElement(By.css(".a-main-title--info")).getText() == "BYLI JSTE ÚSPĚŠNĚ ODHLÁŠENI.")
    } else {
      console.log("Uživatel je již odhlášený.")
    }
  }
  async function prihlaseni() {
    await driver.get("https://test.kokiskashop.cz//cz/prihlaseni/")
    vars["loginurl"] = await driver.executeScript("return window.location.href")
    assert(vars["loginurl"].toString() == "https://test.kokiskashop.cz/cz/prihlaseni/")
    vars["title-size"] = await driver.findElements(By.xpath("//*[@id=\"snippet-front-login\"]/div/section/div/h2")).length
    if (!!await driver.executeScript("return (arguments[0] > 0)", vars["title-size"])) {
      odhlaseni()
    } else {
      await driver.get("https://test.kokiskashop.cz//cz/prihlaseni/")
      assert(await driver.getTitle() == "Přihlášení | Kokiskashop.cz")
      LoginFailTest()
      LoginValidCredentials()
      LoginSuccessTest()
      odhlaseni()
    }
  }
  async function loginFailTest() {
    await driver.get("https://test.kokiskashop.cz/cz/prihlaseni/")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("login")).sendKeys("test")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("test")
    await driver.findElement(By.css(".btn--login")).click()
    {
      const elements = await driver.findElements(By.xpath("//input[@class=\'btn--login submit-form\']"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".login-form__error")).getText() == "Login nebo heslo nejsou platné.")
  }
  async function loginValidCredentials() {
    vars["username2"] = "anezka.pulkrtova"
    vars["password2"] = "tha2Z3FK"
  }
  async function loginSuccessTest() {
    await driver.get("https://test.kokiskashop.cz/cz/prihlaseni/")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("login")).sendKeys(vars["username2"])
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys(vars["password2"])
    await driver.findElement(By.css("label:nth-child(2)")).click()
    await driver.findElement(By.css(".btn--login")).click()
  }
  async function kosik1krok() {
    kosiknavigace()
    prazdnykosik()
    await driver.get("https://test.kokiskashop.cz//cz/kosik/produkty/")
    {
      const elements = await driver.findElements(By.css(".cart-nav__wrap"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".page-cart__subtitle"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-items-container:nth-child(2) > .cart-item"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-items-container:nth-child(2) .cart-item__image"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-items-container:nth-child(2) .cart-item__code"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-item__price-per-piece > strong"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-item__delete-sign"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-items__title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-item--special .cart-item__availability"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-item__price:nth-child(2) > strong"))
      assert(elements.length)
    }
    vars["specialItemSize"] = await driver.findElements(By.xpath("//div[@id=\'snippet-front-basket-ste1-content\']/div[3]/div")).length
    if (!!await driver.executeScript("return (arguments[0] > 0)", vars["specialItemSize"])) {
      do {
        {
          const elements = await driver.findElements(By.id("add-special"))
          assert(elements.length)
        }
        await driver.findElement(By.id("add-special")).click()
        vars["specialItemSize"] = await driver.findElements(By.xpath("//div[@id=\'snippet-front-basket-ste1-content\']/div[3]/div")).length
      } while(!!await driver.executeScript("return (arguments[0] > 0)", vars["specialItemSize"]))
    } else {
      {
        const elements = await driver.findElements(By.css(".cart-item--special .cart-item__availability"))
        assert(!elements.length)
      }
      {
        const elements = await driver.findElements(By.id("add-special"))
        assert(!elements.length)
      }
      console.log(vars["specialItemSize"])
    }
    await driver.findElement(By.css(".cart-item__quantity-control:nth-child(1)")).click()
    {
      const elements = await driver.findElements(By.css(".cart-items__price-container"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-buttons__button--gray"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-buttons__button--green"))
      assert(elements.length)
    }
    do {
      vars["discountCode"] = await driver.executeScript("return prompt(\'Slevový kód\')")
      console.log(vars["discountCode"])
    } while(!!await driver.executeScript("return (arguments[0] == null)", vars["discountCode"]))
    vars["discountCodeSize"] = await driver.findElements(By.xpath("//*[@id=\"snippet-front-discount-code\"]/div[1]/span[1]")).length
    if (!!await driver.executeScript("return (arguments[0] > 0)", vars["discountCodeSize"])) {
      {
        const elements = await driver.findElements(By.css(".cart-discount-code__button-icon"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cart-discount-code__button > span"))
        assert(elements.length)
      }
      {
        const element = await driver.findElement(By.id("discount-code"))
        assert(await element.isEnabled())
      }
      await driver.findElement(By.xpath("//*[@id=\"snippet-front-discount-code\"]/div[1]/span[1]")).click()
      await driver.findElement(By.id("discount-code")).sendKeys(vars["discountCode"])
      {
        const elements = await driver.findElements(By.xpath("//button[@class=\'cart-discount-code__submit\']"))
        assert(elements.length)
      }
      await driver.findElement(By.xpath("//button[@class=\'cart-discount-code__submit\']")).click()
      await driver.wait(until.elementLocated(By.css(".cart-discount-code__value")), 5000)
      {
        const elements = await driver.findElements(By.id("discount-message"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.linkText("×"))
        assert(elements.length)
      }
    }
    vars["cart-item-size"] = await driver.findElements(By.xpath("//*[@class=\'cart-item\']")).length
    await driver.findElement(By.css(".cart-buttons__button--green")).click()
  }
  async function prazdnykosik() {
    await driver.get("https://test.kokiskashop.cz//cz/kosik/produkty/")
    vars["cartitemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item\']")).length
    console.log("Počet produktů v košíku je: vars["cartitemSize"]")
    if (!!await driver.executeScript("return (arguments[0] > 0)", vars["cartitemSize"])) {
      do {
        await driver.findElement(By.css(".cart-item__delete-sign")).click()
        await driver.sleep(2000)
        vars["cartitemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item\']")).length
      } while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartitemSize"]))
    } else if (!!await driver.executeScript("return (arguments[0] < 1)", vars["cartitemSize"])) {
      {
        const elements = await driver.findElements(By.css(".cart-empty__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".page-cart__title"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cart-empty__text"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".page-cart__link"))
        assert(elements.length)
      }
      await driver.findElement(By.css(".header__cart-quantity-badge")).click()
      {
        const elements = await driver.findElements(By.css(".cart-buttons__button"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.xpath("//button[@class=\'header-search__search-btn\']"))
        assert(elements.length)
      }
      await driver.findElement(By.css(".cart-buttons__button")).click()
      {
        const elements = await driver.findElements(By.css(".header-search__search-btn"))
        assert(elements.length)
      }
    }
  }
  async function kosik2krok() {
    await driver.get("https://test.kokiskashop.cz//cz/kosik/doprava/")
    {
      const elements = await driver.findElements(By.css(".cart-content"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".page-cart__title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".page-cart__subtitle"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".page-cart__subtitle"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__message-text"))
      assert(elements.length)
    }
    await driver.switchTo().frame(0)
    await driver.switchTo().defaultContent()
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(1) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(1) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(1) > .cart-post__price-box"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(1) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(1) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(1) > .cart-post__price-box"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(2) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(2) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(2) > .cart-post__price-box"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(3) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(3) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-post__list:nth-child(3) > .cart-post__point:nth-child(3) > .cart-post__price-box"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(2) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(2) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(2) > .cart-post__price-box"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".delivery-selectable:nth-child(2) .cart-post__name")).click()
    await driver.wait(until.elementLocated(By.css(".modal-window__overlay")), 30000)
    {
      const elements = await driver.findElements(By.css(".branch_search-input"))
      assert(elements.length)
    }
    {
      const element = await driver.findElement(By.css(".branch_search-input"))
      assert(await element.isEnabled())
    }
    await driver.findElement(By.css(".branch_search-input")).sendKeys("36001")
    await driver.findElement(By.css(".branch_result-item > div:nth-child(2)")).click()
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("selectBranchId827")).isSelected())
    {
      const elements = await driver.findElements(By.css("label > div:nth-child(1)"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".btn--cart"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".btn--cart")).click()
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(3) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(3) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(3) > .cart-post__price-box"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(4) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(4) .cart-post__name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(5) .cart-post__icon"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".delivery-selectable:nth-child(5) .cart-post__name"))
      assert(elements.length)
    }
    await driver.findElement(By.id("order_submit")).click()
  }
  async function kosik3krok() {
    CartCredentials()
    await driver.get("https://test.kokiskashop.cz//cz/kosik/informace-o-vas/")
    {
      const elements = await driver.findElements(By.css(".page-cart__title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-form__half > .page-cart__subtitle"))
      assert(elements.length)
    }
    {
      const element = await driver.findElement(By.id("name"))
      assert(await element.isEnabled())
    }
    {
      const element = await driver.findElement(By.id("email"))
      assert(await element.isEnabled())
    }
    {
      const element = await driver.findElement(By.id("tel"))
      assert(await element.isEnabled())
    }
    {
      const element = await driver.findElement(By.id("dstreet"))
      assert(await element.isEnabled())
    }
    {
      const element = await driver.findElement(By.id("dstreetnum"))
      assert(await element.isEnabled())
    }
    {
      const element = await driver.findElement(By.id("dcity"))
      assert(await element.isEnabled())
    }
    {
      const element = await driver.findElement(By.id("dzip"))
      assert(await element.isEnabled())
    }
    await driver.findElement(By.id("saveOrder")).click()
    {
      const elements = await driver.findElements(By.css(".cart-form__error-global-title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("terms_error"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".alert_name_text"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".alert_email"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".alert_tel_text"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("terms_label"))
      assert(elements.length)
    }
    await driver.findElement(By.id("terms_label")).click()
    await driver.findElement(By.id("name")).sendKeys(vars["name_surname"])
    await driver.findElement(By.id("email")).sendKeys(vars["email"])
    await driver.findElement(By.id("tel")).sendKeys(vars["phone"])
    await driver.findElement(By.css("#terms_label > .ajax")).click()
    await driver.wait(until.elementLocated(By.css(".page__title--conditions")), 30000)
    await driver.findElement(By.id("Layer_1")).click()
    {
      const elements = await driver.findElements(By.css(".cart-form__info:nth-child(5)"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".cart-form__info > .ajax")).click()
    await driver.wait(until.elementLocated(By.css(".page__title")), 30000)
    await driver.findElement(By.id("Layer_1")).click()
    {
      const elements = await driver.findElements(By.css(".cart-buttons__button--gray"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("saveOrder"))
      assert(elements.length)
    }
    await driver.findElement(By.id("saveOrder")).click()
  }
  async function cartCredentials() {
    vars["name_surname"] = "Anežka Pulkrtová"
    vars["email"] = "anezka.pulkrtova@kokiska.cz"
    vars["phone"] = "724576230"
  }
  async function kosik4krok() {
    await driver.get("https://test.kokiskashop.cz//cz/kosik/rekapitulace/")
    {
      const elements = await driver.findElements(By.css(".page-cart__title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-confirm__half:nth-child(1) > .page-cart__subtitle"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-confirm__half--right > .page-cart__subtitle"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-confirm__list > .cart-confirm__list-title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-confirm__price-box > .cart-confirm__item-value"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-confirm__all-price-dph"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-buttons__button--gray"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.id("finishOrder"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-eet"))
      assert(elements.length)
    }
    await driver.findElement(By.id("finishOrder")).click()
    await driver.findElement(By.css(".cart-buttons__button")).click()
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.name("sent")).click()
    await driver.wait(until.elementLocated(By.css(".cart-final__status-icon")), 30000)
    {
      const elements = await driver.findElements(By.css(".page-cart__title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".cart-final__text > strong"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.linkText("Pokračovat k nákupu"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Pokračovat k nákupu")).click()
  }
  it('kosik', async function() {
    await driver.get("https://test.kokiskashop.cz//")
    vars["t"] = "1"
    const times = 2
    for(let i = 0; i < times; i++) {
      vars["topMenuLink"] = await driver.findElements(By.xpath("//*[@class=\'top-bar__menu-link\']")).length
      if (!!await driver.executeScript("return (arguments[0] == 1)", vars["t"])) {
        if (!!await driver.executeScript("return (arguments[0] < 6)", vars["topMenuLink"])) {
          odhlaseni()
        }
      } else if (!!await driver.executeScript("return (arguments[0] == 2)", vars["t"])) {
        if (!!await driver.executeScript("return (arguments[0] > 4)", vars["topMenuLink"])) {
          prihlaseni()
        }
      }
      kosik1krok()
      kosik2krok()
      kosik3krok()
      kosik4krok()
      vars["t"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["t"])
    }
  })
})
