// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('objednavkaTest1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('objednavkaTest1', async function() {
    await driver.get("http://admin-test.kokiska.cz/")
    await driver.findElement(By.id("ui-id-8")).click()
    vars["w"] = "1"
    while(!!await driver.executeScript("return (arguments[0] < 2)", vars["w"])) {
      await driver.findElement(By.css("tr.row-orders:nth-child" + (vars["w"]) + "strong")).click()
      vars["w"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["w"])
    }
  })
})
