// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pokus-objednavky_2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('pokus-objednavky_2', async function() {
    await driver.get("http://admin-test.kokiska.cz/")
    vars["a"] = await driver.findElements(By.xpath("//*[@id=\"snippet-order-state\"]/li/a")).length
    console.log(vars["a"])
    vars["i"] = "3"
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["a"])) {
      vars["2"] = await driver.findElement(By.css("#snippet-order-state > li:nth-child(vars["i"]) > .ajax")).getText()
      console.log(vars["2"])
      vars["2"] = await driver.executeScript("return parseInt(arguments[0].match(/\\d/g).join(\'\'), 10)", vars["2"])
      console.log(vars["2"])
      await driver.findElement(By.css("#snippet-order-state > li:nth-child(vars["i"]) > .ajax")).click()
      if (!!await driver.executeScript("return (arguments[0] == 0)", vars["2"])) {
        {
          const elements = await driver.findElements(By.css("#snippet-orders-list > table > tbody > tr > td > div"))
          assert(elements.length)
        }
        assert(await driver.findElement(By.css("#snippet-orders-list > table > tbody > tr > td > div")).getText() == "Zadanému výběru neodpovídají žádné objednávky")
        assert(await driver.findElement(By.css("#snippet-orders-list > div > div > span")).getText() == "0-0 z 0")
      } else if (!!await driver.executeScript("return (0 < arguments[0] < 51)", vars["2"])) {
        vars["x"] = await driver.findElement(By.css("#snippet-orders-list > div > div > span")).getText()
      } else {
      }
      vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
    }
  })
})
