// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('poštovné', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('poštovné', async function() {
    await driver.get("http://admin-test.kokiska.cz/")
    await driver.findElement(By.css(".dropdown:nth-child(8) span")).click()
    vars["variationSize"] = await driver.findElements(By.xpath("//*[@class=\'variationContent\']")).length
    vars["variation1"] = await driver.findElement(By.css(".variationItem:nth-child(1) .variationHeader")).getText()
    vars["variation2"] = await driver.findElement(By.css(".variationItem:nth-child(2) .variationHeader")).getText()
    vars["variation3"] = await driver.findElement(By.css(".variationItem:nth-child(3) .variationHeader")).getText()
    vars["variation4"] = await driver.findElement(By.css(".variationItem:nth-child(4) .variationHeader")).getText()
    vars["variation5"] = await driver.findElement(By.css(".variationItem:nth-child(5) .variationHeader")).getText()
    vars["variation6"] = await driver.findElement(By.css(".variationItem:nth-child(6) .variationHeader")).getText()
    vars["variation7"] = await driver.findElement(By.css(".variationItem:nth-child(7) .variationHeader")).getText()
    vars["variation8"] = await driver.findElement(By.css(".variationItem:nth-child(8) .variationHeader")).getText()
    vars["deliveryCZ"] = await driver.executeScript("return [arguments[0], arguments[1], arguments[2], arguments[3], arguments[4], arguments[5], arguments[6], arguments[7]]", vars["variation1"],vars["variation2"],vars["variation3"],vars["variation4"],vars["variation5"],vars["variation6"],vars["variation7"],vars["variation8"])
    await driver.findElement(By.css("#specification8 .btn > .fa")).click()
    await driver.findElement(By.linkText("Upravit platební možnosti")).click()
    vars["paymentSize"] = await driver.findElements(By.xpath("//*[@class=\'borderTop borderBottom paymentRow\']")).length
    vars["v1"] = await driver.findElement(By.css(".borderTop:nth-child(1) strong")).getText()
    vars["v2"] = await driver.findElement(By.css(".borderTop:nth-child(2) strong")).getText()
    vars["v3"] = await driver.findElement(By.css(".borderTop:nth-child(3) strong")).getText()
    vars["v4"] = await driver.findElement(By.css(".borderTop:nth-child(4) strong")).getText()
    vars["v5"] = await driver.findElement(By.css(".borderTop:nth-child(5) strong")).getText()
    vars["v6"] = await driver.findElement(By.css(".borderTop:nth-child(6) strong")).getText()
    vars["v7"] = await driver.findElement(By.css(".borderTop:nth-child(7) strong")).getText()
    vars["v8"] = await driver.findElement(By.css(".borderTop:nth-child(8) strong")).getText()
    vars["v9"] = await driver.findElement(By.css(".borderTop:nth-child(9) strong")).getText()
    vars["v10"] = await driver.findElement(By.css(".borderTop:nth-child(10) strong")).getText()
    vars["v11"] = await driver.findElement(By.css(".borderTop:nth-child(11) strong")).getText()
    vars["v12"] = await driver.findElement(By.css(".borderTop:nth-child(12) strong")).getText()
    vars["v13"] = await driver.findElement(By.css(".borderTop:nth-child(13) strong")).getText()
    vars["v14"] = await driver.findElement(By.css(".borderTop:nth-child(14) strong")).getText()
    vars["v15"] = await driver.findElement(By.css(".borderTop:nth-child(15) strong")).getText()
    vars["v16"] = await driver.findElement(By.css(".borderTop:nth-child(16) strong")).getText()
    vars["v17"] = await driver.findElement(By.css(".borderTop:nth-child(17) strong")).getText()
    vars["v18"] = await driver.findElement(By.css(".borderTop:nth-child(18) strong")).getText()
    vars["v19"] = await driver.findElement(By.css(".borderTop:nth-child(19) strong")).getText()
    await driver.findElement(By.css(".btn-warning")).click()
    vars["paymentCZ"] = await driver.executeScript("return [arguments[0], arguments[1], arguments[2], arguments[3], arguments[4], arguments[5], arguments[6], arguments[7], arguments[8], arguments[9], arguments[10], arguments[11], arguments[12], arguments[13], arguments[14], arguments[15], arguments[16], arguments[17], arguments[18]]", vars["v1"],vars["v2"],vars["v3"],vars["v4"],vars["v5"],vars["v6"],vars["v7"],vars["v8"],vars["v9"],vars["v10"],vars["v11"],vars["v12"],vars["v13"],vars["v14"],vars["v15"],vars["v16"],vars["v17"],vars["v18"],vars["v19"])
    console.log(vars["paymentCZ"])
  })
})
