// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('storno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('storno', async function() {
    await driver.get("http://admin-test.kokiska.cz/")
    vars["storno_k"] = await driver.findElement(By.css("li:nth-child(52) .count")).getText()
    await driver.findElement(By.id("ui-id-10")).click()
    await driver.sleep(1000)
    vars["storno_g"] = await driver.findElement(By.css("li:nth-child(52) .count")).getText()
    await driver.findElement(By.id("ui-id-8")).click()
    await driver.sleep(1000)
    vars["storno"] = await driver.findElement(By.css("li:nth-child(52) .count")).getText()
    console.log(vars["storno_k"])
    console.log(vars["storno_g"])
    console.log(vars["storno"])
    vars["storno_k"] = await driver.executeScript("return parseInt(arguments[0].match(/\\d/g).join(\'\'), 10)", vars["storno_k"])
    vars["storno_g"] = await driver.executeScript("return parseInt(arguments[0].match(/\\d/g).join(\'\'), 10)", vars["storno_g"])
    vars["storno"] = await driver.executeScript("return parseInt(arguments[0].match(/\\d/g).join(\'\'), 10)", vars["storno"])
    console.log(vars["storno_k"])
    console.log(vars["storno_g"])
    console.log(vars["storno"])
    vars["a"] = await driver.executeScript("return arguments[0] + arguments[1] == arguments[2]", vars["storno_k"],vars["storno_g"],vars["storno"])
    assert(vars["a"].toString() == "true")
    vars["text"] = await driver.findElements(By.xpath("//*[@data-id=\'12\']")).length
    console.log(vars["text"])
    vars["txt"] = await driver.findElement(By.css(".row-orders:nth-child(1) .medium")).getText()
    console.log(vars["stornoSize"])
    vars["pagenationTotalCount"] = await driver.findElement(By.css(".pagenationTotalCount")).getText()
    vars["pagenationTotalCount"] = await driver.executeScript("return arguments[0].substr(7,10)", vars["pagenationTotalCount"])
    if (!!await driver.executeScript("return (arguments[0] > 50)", vars["pagenationTotalCount"])) {
      vars["stornoSize"] = await driver.findElements(By.xpath("//div[@id=\'snippet-orders-list\']/table/tbody/tr/td/table/tbody/tr/td[5]")).length
      assert(vars["stornoSize"].toString() == "50")
    }
    vars["pagenationTotalCount"] = await driver.executeScript("return parseInt(arguments[0].match(/\\d/g).join(\'\'), 10)", vars["pagenationTotalCount"])
    console.log(vars["pagenationTotalCount"])
    vars["a"] = await driver.executeScript("return Number (arguments[0]) / 50", vars["pagenationTotalCount"])
    console.log(vars["a"])
    vars["a"] = await driver.executeScript("return Math.ceil(Number (arguments[0]) / 50)", vars["pagenationTotalCount"])
    console.log(vars["a"])
    await driver.findElement(By.css(".pagination li:nth-child(16) > .ajax")).click()
    await driver.sleep(1500)
    vars["pagenationLast"] = await driver.findElement(By.xpath("//*[@id=\"snippet-orders-list\"]/div/ul/li[14]/a")).getText()
    await driver.sleep(2000)
    assert(vars["pagenationLast"].toString() == "vars["a"]")
  })
})
