// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
//const assert = require('assert');

var castedotazy = require('mocha');
var describe = castedotazy.describe;
var it = castedotazy.it;
var assert = require('chai').assert;

describe('castedotazy', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function kosikprazdny() {
    vars["url"] = await driver.executeScript("return window.location.href")
    if (!!await driver.executeScript("return (arguments[0] !== \'https://www.kokiskashop.cz/cz/kosik/produkty/\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//cz/kosik/produkty/")
    }
    vars["topMenuLinkSize"] = await driver.findElements(By.xpath("//*[@class=\'top-bar__menu-link\']")).length
    if (!!await driver.executeScript("return (arguments[0] < 5)", vars["topMenuLinkSize"])) {
      vars["pageWrapSize"] = await driver.findElements(By.xpath("//*[@class=\'page__wrap\']")).length
      assert(vars["pageWrapSize"].toString() == "2")
      vars["columnSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'extended-cart-panel__column\')]")).length
      assert(vars["columnSize"].toString() == "3")
      vars["titleSize"] = await driver.findElements(By.xpath("//*[@class=\'extended-cart-panel__title\']")).length
      assert(vars["titleSize"].toString() == "vars[" + "columnSize" + "]")
      assert(await driver.findElement(By.xpath("//html/body/section[1]/section/div/div[1]/h2/strong")).getText() == "Nastavení")
      assert(await driver.findElement(By.xpath("//html/body/section[1]/section/div/div[1]/div[1]/label")).getText() == "Cizí měna")
    }
    if (!!await driver.executeScript("return (arguments[0] >= 5)", vars["topMenuLinkSize"])) {
      vars["cartItemSize"] = await driver.findElements(By.xpath("//div[@class=\'cart-items-container\']/div[@class=\'cart-item\']")).length
      while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
        await driver.findElement(By.css(".cart-item__delete-sign")).click()
        await driver.sleep(2000)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//div[@class=\'cart-items-container\']/div[@class=\'cart-item\']")).length
        console.log(vars["cartItemSize"])
      }
    } else if (!!await driver.executeScript("return (arguments[0] < 5)", vars["topMenuLinkSize"])) {
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item cart-item--admin\']")).length
      while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
        await driver.findElement(By.css(".cart-item__delete-sign")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item cart-item--admin\']")).length
      }
    }
    kosiknavigace()
    {
      const elements = await driver.findElements(By.css(".cart-empty__image"))
      assert(elements.length)
    }
    {
      const attribute = await driver.findElement(By.css("img.cart-empty__image")).getAttribute("src")
      vars["imgurl"] = attribute
    }
    assert(vars["imgurl"].toString() == "https://www.kokiskashop.cz/admin-prod/public/images//empty-cart.jpg")
    {
      const attribute = await driver.findElement(By.css("img.cart-empty__image")).getAttribute("alt")
      vars["txt1"] = attribute
    }
    assert(vars["txt1"].toString() == "Prázdný košík")
    assert(await driver.findElement(By.xpath("//*[@class=\'page-cart__title\']")).getText() == "Váš košík je prázdný...")
    assert(await driver.findElement(By.xpath("//*[@class=\'cart-empty__text\']")).getText() == "Máme široký sortimet zboží pro dům, zahradu i volný čas. Pokud potřebujete poradit s výběrem vhodného produktu, využijte naši telefonickou podporu. Jsme tu pro Vás.")
    {
      const attribute = await driver.findElement(By.css("a.page-cart__link")).getAttribute("href")
      vars["linkurl"] = attribute
    }
    assert(vars["linkurl"].toString() == "https://www.kokiskashop.cz/cz/kontakt/")
    assert(await driver.findElement(By.xpath("//*[@class=\'cart-buttons__button cart-buttons__button--green\']")).getText() == "Zpět k nákupu")
    {
      const attribute = await driver.findElement(By.css("a.cart-buttons__button--green")).getAttribute("href")
      vars["backurl"] = attribute
    }
    assert(vars["backurl"].toString() == "https://www.kokiskashop.cz/")
    assert(await driver.findElement(By.xpath("//*[@class=\'cart-eet\']")).getText() == "Podle zákona o evidenci tržeb je prodávající povinen vystavit kupujícímu účtenku. Zároveň je povinen zaevidovat přijatou tržbu u správce daně online")
  }
  async function kosiknavigace() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//cz/kosik/produkty/")
    }
    {
      const elements = await driver.findElements(By.xpath("//*[@class=\'cart-nav__wrap\']"))
      assert(elements.length)
    }
    vars["navStepSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step\')]")).length
    vars["navNumberSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-nav__number\']")).length
    vars["navLabelSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-nav__label\']")).length
    vars["navSeparatorSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-nav__separator\']")).length
    {
      const elements = await driver.findElements(By.xpath("//*[@class=\'cart-nav__shadow\']"))
      assert(elements.length)
    }
    {
      const attribute = await driver.findElement(By.css("img.cart-nav__shadow")).getAttribute("src")
      vars["imgurl"] = attribute
    }
    assert(vars["imgurl"].toString() == "https://www.kokiskashop.cz/admin-prod/public/images/cart-shadow.png")
    assert(vars["navStepSize"].toString() == "4")
    assert(vars["navStepSize"].toString() == "vars[" + "navLabelSize" + "]")
    assert(vars["navStepSize"].toString() == "vars[" + "navNumberSize" + "]")
    assert(vars["navSeparatorSize"].toString() == "3")
    {
      const elements = await driver.findElements(By.xpath("//*[@class=\'cart-nav__step  cart-nav__step--active\']"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--active\')]"))
      assert(elements.length)
    }
    if (!!await driver.executeScript("return (arguments[0] == \'https://test.kokiskashop.cz/cz/kosik/produkty/\')", vars["url"])) {
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'cart-item\']")).length
      if (!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
        {
          const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
          vars["activestepurl"] = attribute
        }
        assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/produkty/")
      }
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "0")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "1")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "2")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "3")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    } else if (!!await driver.executeScript("return (arguments[0] == \'https://www.kokiskashop.cz/cz/kosik/doprava/\')", vars["url"])) {
      {
        const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
        vars["activestepurl"] = attribute
      }
      assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/doprava/")
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "1")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "2")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "3")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    } else if (!!await driver.executeScript("return (arguments[0] == \'https://test.kokiskashop.cz/cz/kosik/informace-o-vas/\')", vars["url"])) {
      {
        const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
        vars["activestepurl"] = attribute
      }
      assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/informace-o-vas/")
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "2")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "3")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    } else if (!!await driver.executeScript("return (arguments[0] == \'https://www.kokiskashop.cz/cz/kosik/rekapitulace/\')", vars["url"])) {
      {
        const attribute = await driver.findElement(By.css("a.cart-nav__step--active")).getAttribute("href")
        vars["activestepurl"] = attribute
      }
      assert(vars["activestepurl"].toString() == "https://www.kokiskashop.cz/cz/kosik/rekapitulace/")
      vars["navStepDoneSize"] = await driver.findElements(By.xpath("//*[contains(@class, \'cart-nav__step--done\')]")).length
      assert(vars["navStepDoneSize"].toString() == "3")
      assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__number\')][1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[1]")).getText() == "✔︎")
      assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[1]")).getText() == "4")
    }
    assert(await driver.findElement(By.xpath("//*[contains(@class, \'cart-nav__label\')][1]")).getText() == "Nákupní košík")
    assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[2]/div[2]")).getText() == "Doprava a platba")
    assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[3]/div[2]")).getText() == "Adresa")
    assert(await driver.findElement(By.xpath("//html/body/section[2]/div/div[1]/a[4]/div[2]")).getText() == "Dokončení")
  }
  async function hmotnostS() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(2000)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[5]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Hračky pro nejmenší")).click()
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars[" + "i " + "]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 2 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(1500)
        vars["url"] = await driver.executeScript("return window.location.href")
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      console.log(vars["url"])
    } while(!!await driver.executeScript("return (!arguments[0].includes(\'/kosik/produkty\'))", vars["url"]))
  }
  async function hmotnostM() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[4]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Autodoplňky")).click()
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars[" + "i" + "]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 10 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[1]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Bazény a vířivky")).click()
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars[" + "i" + "]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 30 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'header__cart-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostXL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    {
      const element = await driver.findElement(By.xpath("//*[@id=\"mainmenu\"]/ul/li[1]/a/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Grily a krby")).click()
    await driver.findElement(By.id("box-tab-menu")).click()
    {
      const dropdown = await driver.findElement(By.id("box-tab-menu"))
      await dropdown.findElement(By.xpath("//option[. = 'Od nejdražšího']")).click()
    }
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars[" + "i" + "]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 50 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostXXL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    await driver.findElement(By.id("main-search-inputfield")).sendKeys("marimex trampolína")
    await driver.findElement(By.id("main-search-inputfield")).sendKeys(Key.ENTER)
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars[" + "i" + "]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 70 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@id=\"snippet-front-basket-head\"]/div/div/div[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@id=\"snippet-front-basket-head\"]/div/div/div[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  async function hmotnostXXXL() {
    vars["url"] = await driver.executeScript("return window.location.href")
    console.log(vars["url"])
    if (!!await driver.executeScript("return (arguments[0] == \'chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html\')", vars["url"])) {
      await driver.get("https://www.kokiskashop.cz//")
    }
    {
      const element = await driver.findElement(By.xpath("//*[@class=\'header__cart-icon\']"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["cartItemSize"])) {
      await driver.findElement(By.css(".header__cart-item-delete-img")).click()
      await driver.sleep(500)
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    }
    await driver.findElement(By.id("main-search-inputfield")).sendKeys("věž posilovací dvoupozicová")
    await driver.findElement(By.id("main-search-inputfield")).sendKeys(Key.ENTER)
    vars["i"] = "1"
    do {
      await driver.findElement(By.xpath("//descendant::*[@class=\'product-thumbnail__detail-btn\'][vars[" + "i" + "]]")).click()
      {
        const element = await driver.findElement(By.xpath("//img[@class=\'detail__card-list-icon\']"))
        await driver.actions({ bridge: true }).moveToElement(element).perform()
      }
      vars["catTxt"] = await driver.findElement(By.css(".detail__card-list-cover")).getText()
      if (!!await driver.executeScript("return (arguments[0].includes(\'do 150 kg\'))", vars["catTxt"])) {
        await driver.findElement(By.id("add-to-cart")).click()
        await driver.sleep(500)
        vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
        console.log(vars["cartItemSize"])
      } else {
        vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      }
      vars["cartItemSize"] = await driver.findElements(By.xpath("//*[@class=\'header__cart-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] < 1)", vars["cartItemSize"]))
  }
  it('castedotazy', async function() {
    await driver.get("https://www.kokiskashop.cz//cz/nejcastejsi-otazky-a-odpovedi/")
    vars["faqurl"] = await driver.executeScript("return window.location.href")
    assert(vars["faqurl"].toString() == "https://www.kokiskashop.cz/cz/nejcastejsi-otazky-a-odpovedi/")
    assert(await driver.getTitle() == "Nejčastější otázky | Kokiskashop.cz")
    {
      const elements = await driver.findElements(By.css(".page__title"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".page__text"))
      assert(elements.length)
    }
    vars["faqQuestionSize"] = await driver.findElements(By.xpath("//*[@class=\'faq__box\']")).length
    console.log("Number of questions = vars[" + "faqQuestionSize" + "]")
    vars["i"] = "1"
    while(!!await driver.executeScript("return (arguments[0] > 0)", vars["faqQuestionSize"])) {
      await driver.findElement(By.xpath("//descendant::*[contains(@class, \'faq__status-wrap\')][vars[" + "i" + "]]")).click()
      vars["i"] = await driver.executeScript("return Number (arguments[0]) + 1", vars["i"])
      vars["faqQuestionSize"] = await driver.executeScript("return Number (arguments[0]) - 1", vars["faqQuestionSize"])
    }
  })
})
