// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
//const assert = require('assert');

var mocha = require('mocha');
var {describe, it} = require('mocha');
var assert = require('chai').assert;

mocha.ui('bdd').run(function (failures) {
    process.on('exit', function () {
      process.exit(failures);
    });
  });
  
describe('vyhledavani', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('vyhledavani', async function() {
    await driver.get("https://www.kokiskashop.cz/")
    do {
      do {
        vars["productNumber"] = await driver.executeScript("return prompt(\'Zadejte katalogové číslo produktu popř. název\')")
      } while(!!await driver.executeScript("return (arguments[0] == null)", vars["productNumber"]))
      if (!!await driver.executeScript("return (arguments[0] !== null)", vars["productNumber"])) {
        await driver.findElement(By.id("main-search-inputfield")).sendKeys(vars["productNumber"])
      } else {
        await driver.findElement(By.id("main-search-inputfield")).sendKeys("stůl")
      }
      await driver.findElement(By.css(".header-search__search-btn")).click()
      await driver.findElement(By.id("main-search-inputfield")).sendKeys(Key.ENTER)
      vars["productSize"] = await driver.findElements(By.xpath("//*[@class=\'product-thumbnail product-thumbnail--product-grid-item\']")).length
    } while(!!await driver.executeScript("return (arguments[0] == 0)", vars["productSize"]))
  })
})
